server:
  port: 80

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka/

## 开始后可解决默认降级方法不生效的问题    PaymentFallbackServiceImpl
#feign:
#  hystrix:
#    enabled: true




#设置feign客户端超时时间(OpenFeign默认支持ribbon)  默认是1秒
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间  5秒
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000